apiVersion: v1
kind: Secret
metadata:
  namespace: pml-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: |-
    auth:
      auth_url: http://172.17.9.231:5000
      username: "xialingming"
      password: "xialingming"
      project_id: 7bbfd485c4374affa490bbabfa7e497e
      project_name: "HyperOS-Demo"
      user_domain_name: "Default"
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
---
apiVersion: iaas.pml.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: pml-system
      name: example-provider-secret
      key: credentials
